#!/usr/bin/env node

/*
  DORM (Document Object Render Model)
  author: Mariz Melo (c) MIT 2013
  github: marizmelo/DORM
  desc:   dorm program
*/

// DEPENDENCIES
var program = require('commander')  // command line options
  , dorm = require("./lib/core.js");

function range(val) {
  return val.split('..').map(Number);
}

function list(val) {
  return val.split(',');
}

program
  .version('0.0.1')
  .usage('[options] <file>')
  .option('-m, --minify')
  .option('-p, --pretty')
  .option('-r, --range <a>..<b>', 'A range', range)
  .option('-l, --list <items>', 'A list', list)
  .option('-o, --optional [value]', 'An optional value')
  .parse(process.argv);

console.log(' minify: %j', program.minify);
console.log(' int: %j', program.integer);
console.log(' float: %j', program.pretty);
console.log(' optional: %j', program.optional);
program.range = program.range || [];
console.log(' range: %j..%j', program.range[0], program.range[1]);
console.log(' list: %j', program.list);
console.log(' args: %j', program.args);